CREATE TABLE IF NOT EXISTS products (
    product_id UUID PRIMARY KEY NOT NULL,
    quantity BIGINT NOT NULL,
    fragile BOOLEAN,
    weight DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    depth DOUBLE PRECISION NOT NULL
);